
import localFont from "next/font/local";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css'; 
import "./globals.css";
import { ToastProvider } from "@/context/ToastContext";
import { Provider } from "react-redux";
import store from "@/lib/store/store";
import StoreProvider from "./StoreProvider";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "TVS Motor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
        <AuthProvider>
         <ToastProvider>
          <>"hgfgf"</>
        {children}
        <ToastContainer/>
        </ToastProvider>
        </AuthProvider>
        </StoreProvider>
      </body>
    </html>
    
  );
}
